### ISSUE TITLE
lwip compile error - core2 - v1.3.1

### ISSUE THREAD

**Issue by revta** [tanakamasayuki/ESP32LitePack#2]
I was interested in using this library with the core2. I am trying to run the M5liteBasic Example and am getting the following error:

`Arduino: 1.8.13 (Mac OS X), Board: "M5Stack-Core2, Enabled, Default (2 x 6.5 MB app, 3.6 MB SPIFFS), 240MHz (WiFi/BT), 921600, None" `

`Multiple libraries were found for "SD.h"
In file included from ` `/Users/MacUser/Documents/Arduino/libraries/ESP32_Lite_Pack_Library/examples/M5Lite/M5LiteBasic/M5LiteBasic.ino:2:0:`
 `Used: /Users/MacUser/Library/Arduino15/packages/m5stack/hardware/esp32/1.0.6/libraries/SD`
 `Not used: /Applications/Arduino.app/Contents/Java/libraries/SD`
`/Users/MacUser/Documents/Arduino/libraries/ESP32_Lite_Pack_Library/src/M5Lite.h:13:26: fatal error: lwip\sockets.h: No such file or directory`
 `Not used: /Users/MacUser/Documents/Arduino/libraries/SD`
 `#include "lwip\sockets.h"`
`Multiple libraries were found for "WiFi.h"`
                          ^
 `Used: /Users/MacUser/Library/Arduino15/packages/m5stack/hardware/esp32/1.0.6/libraries/WiFi
compilation terminated.`
 `Not used: /Applications/Arduino.app/Contents/Java/libraries/WiFi`
`exit status 1`
`Error compiling for board M5Stack-Core2.`

My environment is setup per the m5stack docs quick start guide, and am able to compile and run the examples provided for the core2 from the default stack libraries. 

Thank you!

**Comment by tanakamasayuki** [comment]
sorry. Windows \ was mixed in the include path.
 
```
#include "lwip\sockets.h"
```

\ -> /

v1.3.2 has been released.

**Comment by revta** [comment]
Fixed! Thank you for the quick response! 

Tested, verified and burned to M5Stack Core2.
